[package]
name = "elemental"
version = "0.1.0"
edition = "2024"

[dependencies]
elemental-core = { path = "../core" }
elemental-loader = { path = "../loader" }
elemental-object = { path = "../object" }
elemental-shared = { path = "../shared" }

[features]
shared = []
loader = []
object = []
full = ["loader", "object", "shared"]
default = ["full"]
