[package]
name = "elemental-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
scc = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
